In [9]:
import pydiffmap
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas as pd
from pydiffmap import diffusion_map as dm
from pydiffmap.visualization import embedding_plot, data_plot

In [10]:
mydmap = dm.DiffusionMap.from_sklearn(n_evecs = 1, alpha = 0.5, epsilon = 'bgh', k=64)

In [11]:
def load_data():
    filename = 'datasets/MI_timesteps.txt'
    with open(filename, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=' ')
        next(reader)
        rows = []
        for row in reader:
            rows.append(row)
        return rows

In [12]:
data_list = load_data()
data = np.array(data_list)
data = data.astype(np.float)
data = data[1000:]

In [13]:
np.shape(data)

(14001, 10)

In [14]:
data_n = np.delete(data, 0, axis=1)

In [15]:
np.shape(data_n)

(14001, 9)

In [16]:
print(data_n)

[[ 0.  2. 97. ...  5.  1. 43.]
 [ 0.  2. 96. ...  5.  1. 45.]
 [ 0.  2. 95. ...  5.  0. 46.]
 ...
 [ 0. 10. 93. ...  2.  1. 40.]
 [ 0. 10. 93. ...  3.  1. 41.]
 [ 0. 11. 91. ...  1.  0. 42.]]


In [17]:
mydmap.fit(data_n)

In [20]:
dmap = mydmap.fit_transform(data_n)

In [22]:
embedding_plot(mydmap)
data_plot(mydmap)

plt.show()

IndexError: index 1 is out of bounds for axis 1 with size 1

<Figure size 432x432 with 0 Axes>